config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'prototypes#index'
  get 'prototypes/sort_popular'  => 'prototypes#sort_popular'
  resources :prototypes, only: [:index, :new, :create, :show, :destroy, :edit, :update] do
    resources :comments, only: [:index, :create, :edit, :update, :destroy]
    resources :likes, only: [:create, :destroy]
   end
  resources :users, only: [:show, :edit, :update]
end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :categories, through: :article_categories
  has_many :article_categories, dependent: :destroy
end

def save_categories(tags)
    current_tags = self.categories.pluck(:name) unless self.categories.nil?
    old_tags = current_tags - tags
    new_tags = tags - current_tags

    # Destroy old taggings:
    old_tags.each do |old_name|
      self.categories.delete Category.find_by(name:old_name)
    end

    # Create new taggings:
    new_tags.each do |new_name|
      article_category = Category.find_or_create_by(name:new_name)
      self.categories << article_category
    end
  end

app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base
  belongs_to :article
  belongs_to :category
  validates :article_id,presence:true
  validates :category_id,presence:true
end

app/models/captured_image.rb
class CapturedImage < ActiveRecord::Base
  belongs_to :prototype

  mount_uploader :content, PrototypeImageUploader

  enum status: %i(main sub)

  validates :content,
            :status,
            presence: true
end

app/models/category.rb
class Category < ActiveRecord::Base
  alidates :name,presence:true,length:{maximum:50}
  has_many :articles, through: :articles_categories
  has_many :articles_categories, dependent: :destroy
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  #association
  belongs_to :user
  belongs_to :prototype
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :prototype, counter_cache: :likes_count
  belongs_to :user
end

app/models/prototype.rb
class Prototype < ActiveRecord::Base
  belongs_to :user
  has_many :captured_images, dependent: :destroy
  has_many :comments
  has_many :likes, dependent: :destroy

  accepts_nested_attributes_for :captured_images, reject_if: :reject_sub_images

  validates :title,
            :catch_copy,
            :concept,
            presence: true

  def reject_sub_images(attributed)
    attributed['content'].blank?
  end

  def set_main_thumbnail
    if captured_images.present?
      return captured_images.main.first.content
    else
      return "noimage-big.png"
    end
  end

  def posted_date
    created_at.strftime('%b %d %a')
  end

  def like_user(user_id)
   likes.find_by(user_id: user_id)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :avatar, UserImageUploader

  has_many :prototypes
  has_many :comments
  has_many :likes, dependent: :destroy

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:name, :profile, :position, :occupation, :avatar])

    devise_parameter_sanitizer.permit(:account_update, keys:[:name, :profile, :position, :occupation, :avatar])
  end

  def after_sign_out_path_for(resource)
    new_user_session_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_prototype
  before_action :set_comment, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, only: [:create]

  def create
    @comment = Comment.create(comment_params)
    respond_to do |format|
      format.html { redirect_to prototype_path(@prototype.id) }
      format.json
    end
  end

  def edit
  end

  def update
    @comment.update(comment_params) if @comment.user_id == current_user.id
    redirect_to prototype_path(@prototype.id)
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy if @comment.user_id == current_user.id
    redirect_to prototype_path(@prototype.id)
  end

  private

  def set_prototype
    @prototype = Prototype.find(params[:prototype_id])
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:content).merge(user_id: current_user.id, prototype_id: @prototype.id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.create(user_id: current_user.id, prototype_id: params[:prototype_id])
    # @likes = Like.where(prototype_id: params[:prototype_id])
    @prototype = Prototype.find(params[:prototype_id])
  end

  def destroy
    like = current_user.likes.find_by(prototype_id: params[:prototype_id])
    like.destroy
    @likes = Like.where(prototype_id: params[:prototype_id])
    @prototype = Prototype.find(params[:prototype_id])
  end
end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController
  before_action :set_prototype, only: [:show, :edit, :update, :destroy]

  def index
    @prototypes = Prototype.includes(:user).page(params[:page]).per(3).order("created_at DESC")
    respond_to do |format|
      format.html
      format.json
    end
  end

  def sort_popular
    @prototypes = Prototype.includes(:user).page(params[:page]).per(5).order("likes_count DESC")
    respond_to do |format|
      format.html
      format.json
    end
  end

  def new
    @prototype = Prototype.new
    @prototype.captured_images.build
  end

  def create
    @prototype = Prototype.new(prototype_params)
    if @prototype.save
      redirect_to :root, notice: 'New prototype was successfully created'
    else
      redirect_to new_prototype_path, alert: 'New prototype was unsuccessfully created'
    end
  end

  def show
    @comment = Comment.new
    @comments = @prototype.comments.includes(:user)
    @prototype = Prototype.find(params[:id])
    # @likes = Like.where(prototype_id: params[:id], user_id: current_user.id)
    @like = Like.find_by(prototype_id: params[:id], user_id: current_user.id)
  end

  def destroy
    if @prototype.user_id == current_user.id
      @prototype.destroy
      redirect_to :root
    else
      redirect_to :root
    end
  end

  def edit
        # @prototype.captured_images.build
    @main_image = @prototype.captured_images.where("status = 0")
    @sub_image = @prototype.captured_images.where("status = 1")
    @image = @prototype.captured_images
  end

  def update
    if @prototype.user_id == current_user.id
      @prototype.update(prototype_params)
      redirect_to root_path
    end
  end

  private

  def set_prototype
    @prototype = Prototype.find(params[:id])
  end

  def prototype_params
    tag_list = params[:tag_list]
    params.require(:prototype).permit(
      :title,
      :catch_copy,
      :concept,
      :user_id,
      captured_images_attributes: [:id, :content, :status]
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  def show
    @prototypes = @user.prototypes
  end

  def edit
  end

  def update
    @user.update(user_params)
    redirect_to :root, notice: 'Your user infomation was successfully updated'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :position,
      :profile,
      :occupation,
      :avatar
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.haml
#comment-list
  .media
    .media-left
      / リンクをつける
      = link_to user_path(comment.user_id) do
        = image_tag(comment.user.avatar.thumb, alt: "user_icon", class: "media-object", style: "width: 64px; height: 64px; border-radius: 30%;")
    .media-body
      %h4.media-heading#top-aligned-media
        = comment.user.name
      %p
        = comment.content
      .function-list
        .btn.comment-btn
          = link_to '削除', prototype_comment_path(comment.prototype.id, comment.id), method: :delete, data: {confirm: 'Are you sure?'}
        .btn.comment-btn
          = link_to '編集', edit_prototype_comment_path(comment.prototype.id, comment.id)

app/views/comments/_form.html.haml
.form
  = form_for [@prototype, @comment] do |f|
    %h4.comment-form
      Write a comment
    .row.comment-form
      .form-group.col-md-10
        = f.text_area :content, placeholder: "Your comments", class: "textform-control", id: "comment_text"
      .form-group.col-md-2
        = f.submit 'COMMENT', class: "btn btn-primary"

app/views/comments/edit.html.haml
.edit_comment_form
  .form
    = form_for [@prototype, @comment] do |f|
      %h4.comment-form
        Edit Comment（編集）
      .row.comment-form
        .form-group.col-md-10
          = f.text_area :content, placeholder: "Your comments", class: "textform-control", id: "comment_text"
        .form-group.col-md-2
          = f.submit 'COMMENT', class: "btn btn-primary"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=US-ASCII", "http-equiv" =>  "Content-Type"}/
    %title Protospace
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    = render "shared/header"
    = render "shared/messages"
    = yield
    = render "shared/footer"

app/views/likes/_like.html.haml
- if user_signed_in?
  - if prototype.like_user(current_user.id)
    = button_to prototype_like_path(prototype_id: prototype.id, id: @like.id), method: :delete, id: "like-button", remote: true do
      = image_tag("icon_red_heart.svg")
      いいね
      %span
        = prototype.likes_count
  - else
    = button_to prototype_likes_path(prototype.id), id: "like-button", remote: true do
      = image_tag("icon_heart.svg")
      いいね
      %span
        = prototype.likes_count
- else
  = image_tag("icon_red_heart.svg")
  %span
    = prototype.likes_count

app/views/likes/create.js.erb
$(".media-right").html("<%= j(render partial: 'like', locals: { prototype: @prototype}) %>");

app/views/likes/destroy.js.erb
$(".media-right").html("<%= j(render partial: 'like', locals: { prototype: @prototype, like: @like }) %>");

app/views/prototypes/_prototype.html.haml
.col-sm-4.col-md-3.proto-content
  .dropdown
    %ul
      %li
        = link_to '編集', edit_prototype_path(prototype.id), method: :get
      %li
        = link_to '削除', prototype_path(prototype.id), method: :delete, data: {confirm: 'Are you sure?'}
  .thumbnail
    = link_to image_tag(prototype.set_main_thumbnail), prototype_path(prototype)
    .caption
      %h3
        = prototype.title
      .proto-meta
        .proto-user
          = link_to prototype.user.name, user_path(prototype.user)
        .proto-posted
          = prototype.posted_date

app/views/prototypes/edit.html.haml
.container.proto-new
  = form_for @prototype do |f|
    = f.hidden_field :user_id, value: current_user.id
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          %h4 Title
          .proto-new-title
            = f.text_field :title, required: true, autofocus: true, placeholder: "Input Title"
      .row
        .col-md-12
          %h4 Main Thumbnail
          .cover-image-upload#main_image_uploader
            = image_tag(@prototype.set_main_thumbnail.large, class: 'img-responsive img-size-fix', style: "margin: 0 auto;")
            = f.fields_for :captured_images, @main_image do |images|
              %img{ class: 'main_image'}
              = images.file_field :content, value: @main_image, id: "main"
              = images.hidden_field :status, value: "main"

        .col-md-12
          %h4 Sub Thumbnails
          %ul.proto-sub-list.list-group
            - @sub_image.length.times do |i|
              %li.list-group-item.col-md-4
                .image-upload
                  /= image_tag(@image.sub[i]&.content, class: 'sub_image img-responsive')
                  = image_tag(@image.sub[i]&.content, class: 'sub_image')
                  = f.fields_for :captured_images, @sub_image[i] do |image|
                    / %img{class: "sub_image#{i}"}
                    = image.file_field :content, value: @sub_image[i]
                    = image.hidden_field :status, value: "sub"
      .row.proto-description
        .col-md-12
          %h4 Catch Copy
          = f.text_field :catch_copy, require: true, placeholder: "Input Catch Copy"
        .col-md-12
          %h4 Concept
          = f.text_area :concept, require: true, placeholder: "Input Concept"
      .row.text-center.proto-btn
        = f.submit "PUBLISH", id: "button", class: "btn btn-lg btn-primary btn-block"

app/views/prototypes/index.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.btn-default.btn-popular
          = link_to "Popular", "/prototypes/sort_popular", id: "popular_btn"
        %li.btn-default.btn-popular
          = link_to "Newest", "/prototypes", id: "newest_btn"
      = link_to "VIEW TAGS", "#", class: "btn btn-default col-lg-1"

.container.proto-list
  .row
    = render partial: 'prototypes/prototype', collection: @prototypes

.text-center
  = paginate @prototypes

app/views/prototypes/new.html.haml
.container.proto-new
  = form_for @prototype do |f|
    = f.hidden_field :user_id, value: current_user.id
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          %h4 Title
          .proto-new-title
            = f.text_field :title, required: true, autofocus: true, placeholder: "Input Title"
      .row
        .col-md-12
          %h4 Main Thumbnail
          .cover-image-upload#main_image_uploader
            = f.fields_for :captured_images do |image|
              %img{ class: 'main_image'}
              = image.file_field :content, required: true
              = image.hidden_field :status, value: "main"
        .col-md-12
          %h4 Sub Thumbnails
          %ul.proto-sub-list.list-group
            - 3.times do |i|
              %li.list-group-item.col-md-4.subpreview
                .image-upload.subpreview
                  = f.fields_for :captured_images do |image|
                    %img{ class: "sub_image#{i}"}
                    = image.file_field :content
                    = image.hidden_field :status, value: "sub"
      .row.proto-description
        .col-md-12
          %h4 Catch Copy
          = f.text_field :catch_copy, require: true, placeholder: "Input Catch Copy"
        .col-md-12
          %h4 Concept
          = f.text_area :concept, require: true, placeholder: "Input Concept"
      .row.text-center.proto-btn
        = f.submit "PUBLISH", id: "button", class: "btn btn-lg btn-primary btn-block"

app/views/prototypes/show.html.haml
.container.proto-page
  %header.row.user-nav
    .col-md-6
      .media
        .media-left
          = link_to user_path(@prototype.user) do
            = image_tag(@prototype.user.avatar.thumb, alt: "profile_photo", class: "media-object", style: "width: 64px; height: 64px;")
        .media-body
          %h4#top-aligned-media.media-heading
            = @prototype.title
          .proto-user
            by
            = link_to "#{@prototype.user.name}", user_path(@prototype.user)
            .degree
              = @prototype.user.position
        .media-right
          = render partial: 'likes/like', locals: {prototype: @prototype}
  .row
    .col-md-9.image-box
      = image_tag(@prototype.set_main_thumbnail.large, class: 'img-responsive img-size-fix', style: "margin: 0 auto;")
    .col-md-3
      %ul.proto-sub-list.list-group
        - @prototype.captured_images.sub.each do |image|
          %li.list-group-item
            = image_tag(image.content, class: 'img-responsive')
  .row.proto-description
    .col-md-3
      %h4 Catch Copy
      %p
        = @prototype.catch_copy
    .col-md-6
      %h4 Concept
      %p
        = @prototype.concept
    .col-md-3
      %h4 Tag List
      %ul.proto-tag-list.list-inline
        %li
          %a{href: "#", class: "btn btn-default"} iPad
        %li
          %a{href: "#", class: "btn btn-default"} wireframe
  .row.proto-comments
    %h4.col-md-12
      Comments
      %span.num
        = "( #{ @comments.count } )"
    #comment-area.col-md-8
      = render partial: "comments/comment", collection: @comments
    = render partial: "comments/form"

app/views/prototypes/sort_popular.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.btn-default.btn-popular
          = link_to "Popular", "/prototypes/sort_popular", id: "popular_btn"
        %li.btn-default.btn-popular
          = link_to "Newest", "/prototypes", id: "newest_btn"
      = link_to "VIEW TAGS", "#", class: "btn btn-default col-lg-1"

.container.proto-list
  .row
    = render partial: 'prototypes/prototype', collection: @prototypes

.text-center
  = paginate @prototypes

app/views/shared/_footer.html.haml
.container
  %footer
    %p &copy; PROTO SPACE 2015.

app/views/shared/_header.html.haml
.navbar.navbar-default.navbar-static-top.navbar-fixed-top
  .container
    %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    .navbar-brand
      = link_to image_tag("logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "36px"), root_path
    .navbar-collapse.collapse.navbar-responsive-collapse
      - if user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li.dropdown
            = link_to "#", class: 'dropdown-toggle', role: 'button', 'aria-expanded' =>  'false', 'data-toggle' => 'dropdown' do
              #{current_user.name}
              %span.caret
            %ul.dropdown-menu{role: "menu"}
              %li
                = link_to 'Edit', edit_user_path(current_user)
              %li
                = link_to 'My Page', user_path(current_user)
              %li
                = link_to 'Logout', destroy_user_session_path, method: :delete
          %li
            .btn.btn-default
              = link_to "New Photo", new_prototype_path, style: "color: #337ab7;"
      - else
        %ul.nav.navbar-nav.navbar-right
          %li
            .btn.btn-primary.navbar-btn
              = link_to 'Get Started', new_user_session_path

app/views/shared/_messages.html.haml
- flash.each do |key, value|
  - if value == notice
    = content_tag(:div, value, class: "alert alert--success")
  - if value == alert
    = content_tag(:div, value, class: "alert alert--danger")

app/views/users/edit.html.haml
.container.user-new.clearfix
  = form_for @user do |f|
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          %h2 Edit
          .user-name_image.row
            .user-name.col-md-10
              = f.text_field :name, placeholder: "Input Username", autofocus: true, required: true
            .user-image.col-md-2
              / %img{ style: "" }
              = f.file_field :avatar
              = image_tag(@user.avatar.thumb, alt: "profile_photo", class: "media-object", style: "width: 75px; height: 75px; border-radius: 50%;")
          .user-email
            = f.text_field :email, placeholder: "Input Email", required: true
        .col-md-12
          %h4 Position
          .user-user-member.row
            .user-name.col-md-12
              = f.text_field :position, placeholder: "Input Position"
          %h4 Profile
          .user-user-profile.row
            .user-name.col-md-12
              = f.text_area :profile, placeholder: "Input Profile", size:"30×4"
          %h4 Occupation
          .user-name_image.row
            .user-name.col-md-12
              = f.text_area :occupation, placeholder: "Input Occupation", size: "30×4"
        .row.text-center.user-btn
          .actions
            = f.submit "SAVE", id: "button", class: "btn btn-lg btn-primary btn-block"

app/views/users/show.html.haml
.container.user-page
  %header.user-nav
    .media
      .media-left
        = image_tag(@user.avatar.thumb, alt: "profile_photo", class: "media-object", style: "width: 64px; height: 64px;")
      .media-body
        %h4#top-aligned-media.media-heading
          = @user.name
          %span.label.label-default.project-number
            29
            %i Projects
        .proto-user
          %span.degree= @user.position
        .row
          .col-md-6
            %h4 Profile
            %p= @user.profile
          .col-md-6
            %h4 Occupation
            %p = @user.occupation
.container.proto-list
  .row
    = render partial: 'prototypes/prototype', collection: @prototypes